apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-iqmlhwqj
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-iqmlhwqj:3beb00ec9ad9f3fb6189868be99ec82c89baaa8f@sha256:544f750bfcb1e0d5829e8d87f688baaaec6eec2eb99bcd72742c92c4880b47e2
        name: container-image  
